version: '3.4'

services:

    db_redis:
        image: redis 

    db_mongo:
        image: mongo

    orderdb:
        image: mcr.microsoft.com/mssql/server

    rabbitmq:
        image: rabbitmq:3-management-alpine


    cube_auction.api:
        image: ${DOCKER_REGISTRY-}cube_auction
        build:
            context: .
            dockerfile: src/Cube_Auction/Cube_Auction.API/Dockerfile



    cube_bid.api:
        image: ${DOCKER_REGISTRY-}cube_bid
        build:
            context: .
            dockerfile: src/Cube_Bid/Cube_Bid.API/Dockerfile

    cube_bid.api_clone:
        image: ${DOCKER_REGISTRY-}cube_bid
        build:
            context: .
            dockerfile: src/Cube_Bid/Cube_Bid.API/Dockerfile
  
    cube_bidssignalr:
        image: ${DOCKER_REGISTRY-}cube_bidssignalr
        build:
            context: .
            dockerfile: src/Cube_BidsSignalR/Cube_BidsSignalR/Dockerfile



