version: '3.4'

services:

    #catalogdb:
    #    image: mongo

    basketdb:
        image: redis #LD redis official image

    orderdb:
        image: mcr.microsoft.com/mssql/server

    rabbitmq:
        image: rabbitmq:3-management-alpine

    #catalog.api:
    #    image: ${DOCKER_REGISTRY-}catalogapi
    #    build:
    #        context: .
    #        dockerfile: src/Catalog/Catalog.API/Dockerfile

    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: src/Basket/Basket.API/Dockerfile

    ordering.api:
        image: ${DOCKER_REGISTRY-}orderingapi
        build:
            context: .
            dockerfile: src/Ordering/Ordering.API/Dockerfile

    cube_auction.api:
        image: ${DOCKER_REGISTRY-}cube_auction
        build:
            context: .
            dockerfile: src/Cube_Auction/Cube_Auction.API/Dockerfile

    #apigateway:
    #    image: ${DOCKER_REGISTRY-}apigateway
    #    build:
    #        context: .
    #        dockerfile: src/ApiGateway/APIGateway/Dockerfile

    #aspnetrunbasics:
    #    image: ${DOCKER_REGISTRY-}aspnetrunbasics
    #    build:
    #        context: .
    #        dockerfile: src/WebApp/AspnetRunBasics/Dockerfile

    #asecondconsumerld:
    #    image: ${DOCKER_REGISTRY-}asecondconsumerld
    #    build:
    #        context: .
    #        dockerfile: src/ASecondConsumerLd/Dockerfile

